-- MySQL Script generated by MySQL Workbench
-- lun 01 nov 2021 22:17:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veterinaria-Patitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veterinaria-Patitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veterinaria-Patitas` ;
USE `veterinaria-Patitas` ;

-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Localidad` (
  `CP` INT NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Tipo_DNI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Tipo_DNI` (
  `idTipo_DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Usuario` (
  `idAcceso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  `Telefono` INT NOT NULL,
  `Localidad_CP` INT NOT NULL,
  `Correo_electronico` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Tipo_DNI_idTipo_DNI` INT NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`idAcceso`),
  INDEX `fk_Usuario_Localidad_idx` (`Localidad_CP` ASC) VISIBLE,
  INDEX `fk_Usuario_Tipo_DNI1_idx` (`Tipo_DNI_idTipo_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Localidad`
    FOREIGN KEY (`Localidad_CP`)
    REFERENCES `veterinaria-Patitas`.`Localidad` (`CP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Tipo_DNI1`
    FOREIGN KEY (`Tipo_DNI_idTipo_DNI`)
    REFERENCES `veterinaria-Patitas`.`Tipo_DNI` (`idTipo_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Contacto` (
  `idContacto` INT NOT NULL,
  `Nombre_y_apellido` VARCHAR(45) NOT NULL,
  `Correo_electronico` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Motivo` VARCHAR(45) NOT NULL,
  `Mensaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Login` (
  `idLogin` INT NOT NULL,
  `Usuario_idAcceso` INT NOT NULL,
  `Fecha_hora` DATETIME NOT NULL,
  `Fecha_de_baja` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Usuario1_idx` (`Usuario_idAcceso` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Usuario1`
    FOREIGN KEY (`Usuario_idAcceso`)
    REFERENCES `veterinaria-Patitas`.`Usuario` (`idAcceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Producto/servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Articulos` (
  `idArticulo` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_Articulos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Articulos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `veterinaria-Patitas`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veterinaria-Patitas`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veterinaria-Patitas`.`Carrito` (
  `idOperacion` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Articulos_idArticulo` INT NOT NULL,
  `Login_idLogin` INT NOT NULL,
  `Monto` DECIMAL(45) NOT NULL,
  PRIMARY KEY (`idOperacion`),
  INDEX `fk_Carrito_Articulos1_idx` (`Articulos_idArticulo` ASC) VISIBLE,
  INDEX `fk_Carrito_Login1_idx` (`Login_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_Articulos1`
    FOREIGN KEY (`Articulos_idArticulo`)
    REFERENCES `veterinaria-Patitas`.`Articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_Login1`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `veterinaria-Patitas`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
